### ISSUE TITLE
oh hai

### ISSUE THREAD

**Issue by MylesBorins** [dtcooper/jewpizza#2]
Been a minute, hope you are well. This is what issues are meant for right?

**Comment by dtcooper** [comment]
Hi @MylesBorins, thank you for filing this important issue. We will address your concern below:

How the fuck are you?!

**Comment by MylesBorins** [comment]
Doing pretty darn well 

Back in Canada, got a house in little Portugal. Ready for the ice to melt.

You?

**Comment by dtcooper** [comment]
Well... Should we maybe NOT have a conversation over GitHub issues?
